### ISSUE TITLE
Migration des SFC vers Nuxt 3

### ISSUE THREAD

**Issue by antoinechassagne** [bdxio/bdxio.site#255]
### Le besoin  ✨

Migration des SFC de Nuxt 2 vers Nuxt 3.

### La conception technique 🔧

Guidelines :
- Ordre : `<script>`, `<template>` puis `<style>`
- Script avec `<script setup lang=ts>`

Ressources :
- Breaking changes from Vue 2 to Vue 3 : https://v3-migration.vuejs.org/breaking-changes/
- Nuxt 3 migration guide https://nuxt.com/docs/migration/overview

#### Components

- [x] `components/association/AssociationSectionPresentation.vue`
- [x] `components/association/AssociationSectionVolunteers.vue`
- [x] `components/association/OpenFeedback.vue`
- [x] `components/homepage/HomepageSectionAbout.vue`
- [x] `components/homepage/HomepageSectionAnnualTheme.vue`
- [x] `components/homepage/HomepageSectionHero.vue`
- [x] `components/homepage/HomepageSectionKeyConcepts.vue`
- [x] `components/homepage/HomepageSectionNews.vue`
- [x] `components/homepage/HomepageSectionSpeaker.vue`
- [x] `components/homepage/HomepageSectionSponsor.vue`
- [x] `components/homepage/HomepageSectionSponsors.vue`
- [x] `components/homepage/HomepageSectionThemes.vue`
- [x] `components/icons/OpenNewWindow.vue`
- [x] `components/jobs/SectionJobs.vue`
- [x] ~~components/layout/grid/Flex-container.vue~~
- [x] ~~components/layout/grid/Flex-item.vue~~
- [x] ~~components/layout/grid/index.js~~
- [x] `components/layout/SectionGuidage.vue`
- [x] `components/layout/TheFooter.vue`
- [x] `components/layout/TheHeader.vue`
- [x] `components/layout/TheNavigation.vue`
- [x] `components/sponsors/SectionBecoreSponsor.vue`
- [x] `components/sponsors/SectionSponsorOffers.vue`
- [x] `components/sponsors/SectionSponsorOffersAndSponsors.vue`
- [x] `components/talk/SpeakerProfile.vue`
- [x] `components/talk/TalkSectionPresentation.vue`
- [x] `components/talk/TalkSectionSpeaker.vue`
- [x] `components/talk/TalkSectionTheme.vue`
- [x] `components/SectionTitle.vue`
- [x] `components/ShowOnYoutube.vue`
- [x] `components/TheCounter.vue`

#### Layouts
- [x] `layouts/error.vue`
- [x] `layouts/homepage.vue`
- [x] `layouts/page.vue`

#### Pages
- [x] `pages/talks/_talkId.vue`
- [x] `pages/talks/index.vue`
- [x] `pages/Asso.vue`
- [x] `pages/Conduct.vue`
- [x] `pages/index.vue`
- [x] `pages/Jobs.vue`
- [x] `pages/Live.vue`
- [x] `pages/Schedule.vue`
- [x] `pages/Sponsors.vue`
- [x] `pages/Sponsors2022.vue`

**Comment by HubM** [comment]
J'ai juste barré Flex-Item et Flex-Container; on repassera dessus quand on fera la couche tailwind

**Comment by HubM** [comment]
j'ai supprimé le composant `GoToTop.vue`, j'avais chopé le code vite fait sur internet et l'implémentation était pas ouf. On se le ré-ecrira à notre sauce pour le projet
